# Generated by Django 5.2.13 on 2026-04-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_users_authors_bookimages_books_categories_events_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'event_books',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='authors',
            options={'managed': True, 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': True, 'verbose_name_plural': 'Categories'},
        ),
    ]
