# Generated by Django 5.2.13 on 2026-04-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_eventbooks_alter_authors_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='name_km',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_km',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
