# Generated by Django 5.2.13 on 2026-04-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_addtocart_remove_cartitems_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='batch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
