# Generated by Django 5.2.13 on 2026-04-17 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_addtocart_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
