# Generated by Django 5.2.13 on 2026-04-24 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0011_role_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('total_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remaining_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_used_up', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Coupons',
                'db_table': 'user_coupons',
                'managed': True,
                'unique_together': {('user', 'coupon')},
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_saved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='novels.orders')),
                ('user_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='novels.usercoupon')),
            ],
            options={
                'verbose_name_plural': 'Coupon Usages',
                'db_table': 'coupon_usages',
                'managed': True,
            },
        ),
    ]
