# Generated by Django 5.2.13 on 2026-04-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0012_coupon_alter_authors_id_alter_categories_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'managed': False, 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': False, 'verbose_name_plural': 'Categories'},
        ),
    ]
