# Generated by Django 5.2.13 on 2026-04-24 19:37

import django.db.models.deletion
from django.db import migrations, models


def populate_coupon_codes(apps, schema_editor):
    UserCoupon = apps.get_model('novels', 'UserCoupon')
    for uc in UserCoupon.objects.all():
        if uc.coupon:
            uc.coupon_code = uc.coupon.code
            uc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0013_alter_authors_options_alter_categories_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercoupon',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(populate_coupon_codes),
        migrations.AlterField(
            model_name='usercoupon',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.coupon'),
        ),
        migrations.AlterUniqueTogether(
            name='usercoupon',
            unique_together={('user', 'coupon_code')},
        ),
    ]
