# Generated by Django 5.2.13 on 2026-04-24 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0014_add_coupon_code_to_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='user_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='novels.usercoupon'),
        ),
    ]
