# Generated by Django 5.2.13 on 2026-04-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping_method',
            field=models.CharField(default='Pick Up', max_length=50),
        ),
    ]
