# Generated by Django 5.2.13 on 2026-04-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0018_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='aba_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
