# Generated by Django 5.2.13 on 2026-05-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0020_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('total_visits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Site Statistics',
                'db_table': 'site_stats',
                'managed': True,
            },
        ),
    ]
