# Generated by Django 5.2.13 on 2026-05-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0021_sitestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='batch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
