# Generated by Django 5.2.13 on 2026-05-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0022_orders_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
