# Generated by Django 5.2.13 on 2026-05-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0023_payments_receipt_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventbooks',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'managed': True},
        ),
    ]
