# Generated by Django 5.2.13 on 2026-05-04 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0024_alter_eventbooks_options_alter_events_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooks',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_books', to='novels.books'),
        ),
        migrations.AddField(
            model_name='eventbooks',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_books', to='novels.events'),
        ),
        migrations.AddField(
            model_name='eventbooks',
            name='flash_sale_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventbooks',
            name='items_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='discount_type',
            field=models.CharField(blank=True, default='Percentage', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.CharField(blank=True, default='Promotion', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='banner_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='eventbooks',
            unique_together={('event', 'book')},
        ),
    ]
