# Generated by Django 5.2.13 on 2026-05-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0025_eventbooks_book_eventbooks_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooks',
            name='flash_sale_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventbooks',
            name='items_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(default='Promotion', max_length=20),
        ),
    ]
